### ISSUE TITLE
Ban handling

### ISSUE THREAD

**Issue by erocs** [Civcraft/AFK-Player-GC#10]
Per https://www.reddit.com/r/Civcraft/comments/3fv5sw/the_new_lag_detecting_auto_banning_afkpgc_is/ctsgvrt

getBanList states "Bans by name are no longer supported and this method will return null when trying to request them" yet that is the banlist type being retrieved. Someday it will break.

Does getBanList return the MC global ban manager? It looks like we should be able to differentiate this ban from others via the reason. It is also saving out a list of banned players though, so why not use a copy of PrisonPearl's ban manager? Alternatively, these bans shouldn't persist across reboots so just keep a list of UUIDs and block players at the async pre-login event.

**Comment by ttk2** [comment]
so should we just request bans though PP?

**Comment by erocs** [comment]
No, it has a separate ban list to better manage alt-bans.

**Comment by erocs** [comment]
Eventually obsoleted by https://github.com/Civcraft/CBanManagement

**Comment by ProgrammerDan** [comment]
Following on, issue superseded by  https://github.com/Civcraft/AFK-Player-GC/issues/26
