### ISSUE TITLE
Caching seems ... flawed

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/AFK-Player-GC#14]
Chunk computation caching index isn't working properly. I'm finding evidence that cache is returning values for different chunks. Investigating.

**Comment by Maxopoly** [comment]
I think I found it, you are doing this in line 128 in LagScanner:

```
long chunkId = (long) chunk.getX() << 32L + (long) chunk.getZ();
```
But addition has a higher priority than shifts (see http://introcs.cs.princeton.edu/java/11precedence/), so you are shifting the x coordinate by (32+ z coordinate) and for example the chunks (16,32) ,(16,-32) and (16,96) would all get the same chunkId. Adding parentheses should fix this, I'll put it in my pull.

**Comment by ProgrammerDan** [comment]
You're still up? Awesome catch. Before you commit to it, can you do some
sample-tests for uniqueness?

Also there are at least 2 other places I know this exact construct is used,
meaning those are currently failing.

**Comment by Maxopoly** [comment]
Couldn't sleep and decided to be productive instead. They are unique with parentheses, increasing or decreasing x causes the id to change by 2^32 and what we add from the y doesn't even get close to that. Also it's not even close to overflowing.

**Comment by ProgrammerDan** [comment]
Sounds like a win. Again, epic catch. I've been rolling around in my head and was coming up blank.

**Comment by ProgrammerDan** [comment]
Addressed by: https://github.com/Civcraft/AFK-Player-GC/pull/15

**Comment by ttk2** [comment]
So I guess we can close this issue?

**Comment by Maxopoly** [comment]
Yeah, I think Dan wanted to do that, but forgot

**Comment by ProgrammerDan** [comment]
Yep passed out first.
