### ISSUE TITLE
Players kicked for AFK without being idle

### ISSUE THREAD

**Issue by erocs** [Civcraft/AFK-Player-GC#2]
We have had numerous reports of players being constantly kicked for being AFK while they are moving around and interactive with the world. This has been going on for a while.

One lead that we got today, one of these players has very recently changed their Mojang name and is thus having their name changed by NameLayer. They are now constantly being kicked for AFK when they shouldn't be.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/5f4d9b04a5cf3ec789b96f9896adc177f8be7f58#diff-35250cb092462f1ea9f47e16d8a7d5d5

**Comment by erocs** [comment]
Wrong patch

**Comment by rourke750** [comment]
https://github.com/Civcraft/AFK-Player-GC/commit/b6b9757f85f5b6ae239be68f3ed586b4557992c3#diff-1f90d672a29fa1fa6823c99f333ddba5
