### ISSUE TITLE
Have admins and players with specific perm not be banned for being in laggy area

### ISSUE THREAD

**Issue by rourke750** [Civcraft/AFK-Player-GC#22]

**Comment by ProgrammerDan** [comment]
PM me the UUIDs, immunities in the config are respected.

Code change not required.

**Comment by rourke750** [comment]
e3a90628-674e-4ea5-9b9a-34c175be61d6

**Comment by ProgrammerDan** [comment]
which admin is likely awake and able to push a new config? no restart required

**Comment by ProgrammerDan** [comment]
sent to TTK, if you have other emails I can send more broadly.

**Comment by ttk2** [comment]
the new config is up.
