### ISSUE TITLE
Supply warnings to players when TPS is good

### ISSUE THREAD

**Issue by erocs** [Civcraft/AFK-Player-GC#23]
With the expected high TPS, scans and subsequent warning bans won't be performed. Let's have the plugin warn players (max every 15min) about laggy areas so this profiling can continue to give players input about their setups. We don't want everyone to forgot to optimize their industry.

**Comment by ProgrammerDan** [comment]
@Maxopoly Do you have any interest in tackling this? No pressure, just on reflection I'm not confident that a newer dev would be able to handle this, and you and I have the most knowledge (currently) about this plugin.

**Comment by Maxopoly** [comment]
Yeah sure, I could do that.
