### ISSUE TITLE
Integrate with CBanManagement

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/AFK-Player-GC#26]
All bans should be issued via CBanManagement; local storage should be removed of bans should be removed.

**Comment by suirad** [comment]
Let me know if you need any info or assistance with this.

**Comment by ProgrammerDan** [comment]
Feel free to jump in and go for it!

Is CBanManagement deployed to main now? If it isn't, we can just make this change in a branch and merge in/deploy once CBan is up.

**Comment by suirad** [comment]
I do not believe it has been deployed, but it is ready to be. Yea branching for now would work. It shouldn't be hard to add it at all. You just pretty much add this to each ban site:
```java
// Example of banning for 5 minutes.
Date expires = new Date();
expires.setMinutes(expires.getMinute()+5);
Ban ban = new Ban(BanLevel.TEMP, "afkpgc", "You have been banned for 5min for lag", expires);
cbanman_plugin.banPlayer(player, ban);

```

**Comment by ProgrammerDan** [comment]
That's great. All bans in BotDetector happen in one or two functions, so that should be a quick-n-easy change.

**Comment by suirad** [comment]
Yup, should be quick and easy. Also, .banPlayer works with either UUID or Player. If you don't want the ban to expire, just disregard the Date object and trim it from the end of the Ban constructor.

**Comment by Maxopoly** [comment]
After reading a modmail it just struck me that we completly forgot this and because of that all AFKPGC bans are permanent.

**Comment by ttk2** [comment]
yay, how much work is it to fix?

**Comment by suirad** [comment]
Should only be a few lines to change.

**Comment by ProgrammerDan** [comment]
I'm about to look through CBan anyway, I'll do this quick.

**Comment by ProgrammerDan** [comment]
Integration should be straightforward, but the lack of a "unban all by plugin" function means I'll still have to maintain a list of "bans" for unbanning within AFKPGC. Part of my todo will be to add an unban by plugin function to CBan, then I'll come back to this and finish stripping out the old code.

**Comment by suirad** [comment]
Wouldn't using time based bans make you not need to keep track of them in
AFKPGC?

**Comment by ProgrammerDan** [comment]
AFKPGC unbans everyone if conditions improve (shortening their sentences). So to preserve that function, I'll maintain the list and simply issue unbans via CBan.

I've taken the soft-depends approach, so this'll still work just fine without CBan, and fine with.

**Comment by suirad** [comment]
Should be closed.

**Comment by ProgrammerDan** [comment]
Yeah true, has been done a while!
