### ISSUE TITLE
Admin tool to list and teleport to highest discovered lag spots

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/AFK-Player-GC#27]
Two changes:

1) add a command to list worst lag sources in order of worst to best. This means a list needs to be maintain of laggy locations independent of player resolution by moving away. Could/should tie into LagScanner and keep track on a chunk by chunk basis.

2) Add a command to teleport to identified lag sources; "/afklag start" command should start a session of teleporting to lag sources. Current and new admins joining the game can simply type "/afknext" to go to the next one that hasn't been visited, making it easy for the team to cycle through the list.

**Comment by Maxopoly** [comment]
Idk how to assign myself from mobile, but I'll do that

**Comment by ProgrammerDan** [comment]
Alright. If you don't I'm planning to do it tonight.

**Comment by ProgrammerDan** [comment]
@Maxopoly Have you started, my friend?

**Comment by Maxopoly** [comment]
I fixed a lot of other stuff earlier today, I havent started with this, but I'll get it done today.

**Comment by ProgrammerDan** [comment]
Don't worry about it. I started, I'll have it done by tonight. You're doing great work :D

**Comment by Maxopoly** [comment]
okay

**Comment by rourke750** [comment]
@ProgrammerDan is this done?

**Comment by ProgrammerDan** [comment]
Yeah left instruction for use and for TTK to stage, should be online.

Op yourself, and use /afkpgc inv to teleport around.

If there are console errors pass them along.

**Comment by ProgrammerDan** [comment]
@Rourke750 is it working for you?

**Comment by rourke750** [comment]
Yep, took me to my house.  Didn't see any issue there so moved on <_>

**Comment by ProgrammerDan** [comment]
;P

Yeah it'll take you to any chunks with weight > 120 iirc. might be info overload, but whatever's going on isn't tripping the "area scan".

**Comment by rourke750** [comment]
Is there a reset command though to start at the beginning or go backwards?

**Comment by ProgrammerDan** [comment]
No. Once a spot is marked it doesn't bring you back to it -- order of visit isn't tracked. As new chunks are identified they are sorted into the same list that you visit, so if something "worse" shows up while your visiting areas it'll be your next stop instead. 

Do we need a way to mark or flag chunks you've visited for later return?

**Comment by rourke750** [comment]
That would be nice, pls.

**Comment by ProgrammerDan** [comment]
ok, I'll make a new issue
