### ISSUE TITLE
Custom event on afk/lag kick/ban warning

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/AFK-Player-GC#30]
A LagBanWarningEvent and AFKKickWarnEvent would be really nice

**Comment by ttk2** [comment]
What would we use it for? I mean what other plugin needs that info.

**Comment by TealNerd** [comment]
Well if we use the guide/info plugin I made or something similar it would benefit.

**Comment by ttk2** [comment]
I realised that when going through the rest of my github email. Carry on.

**Comment by TealNerd** [comment]
kk
