### ISSUE TITLE
Issue with builds and maven

### ISSUE THREAD

**Issue by TealNerd** [Civcraft/AFK-Player-GC#32]
the pom has the version as 1.3.5-${build.version} which makes the version in the maven repo literally that. This means AFKPGC can't be added as a maven dependency because maven doesn't read 1.3.5-${build.version} as a literal string and can't find the version in the repo

**Comment by Maxopoly** [comment]
The build server read that as null anyway, no idea why it was there. Might be an obscure leftover from the original AFKPGC code. Anyway I fixed it https://github.com/Civcraft/AFK-Player-GC/commit/9418057649b4d03c09407f42833a76a0dd75c348
