### ISSUE TITLE
Pre-analyze location

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/AFK-Player-GC#6]
Based on some discussion with ttk, @Maxopoly let's modify BotDetector to have a second "below perfect" threshold at which point it starts keeping track of player locations. That way, if we then fall below the "aggressive" threshold, we'll start prioritizing likely lag drivers right away without additional delay.

Bonus: it'll allow better sample lengths for location, which will help the bounds detector be more accurate.

**Comment by ttk2** [comment]
So long as running it isn't too laggy in and of itself it seems to me that we would want to collect as much data as possible.

**Comment by Maxopoly** [comment]
Very good idea. How laggy it is would need some testing, but it should be very easy to implement, I'll work a bit on it later.

**Comment by ProgrammerDan** [comment]
Thanks Max! I doubt this will be super laggy, at worst it'll just use up a bit more memory a bit sooner.

**Comment by ProgrammerDan** [comment]
Addressed in #7
